name: lomi-server-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs